### PR TITLE
Added divinerpg. to entity registration

### PR DESCRIPTION
**Pull request by Adaptivity**
Also, fixed some missing names. Tested all names present in-game.

### CODE REVIEW

**Comment by Eternaldoom** [comment]
There is no reason to put that prefix before the entity names. It is automatically assigned by the FML mod entity registry. The reason the other names are needed is that we map the entity classes to new names in the vanilla registry to allow spawn eggs.

**Comment by Adaptivity** [comment]
So, all names will be doubled forever? Or you fix them later?

**Comment by Eternaldoom** [comment]
Yeah they will be doubled.

**Comment by Adaptivity** [comment]
And what reason to double them? No other mods do this so. And my PR doesn't break anything except compatibility with old saves. But I think no one plays on 1.7.10 with DivineRPG right now. Also, many mods adds registration prefix to .lang file. For example: https://github.com/ForestryMC/Forestry-Localization/blob/master/assets/forestry/lang/en_US.lang
So, what bad if you pull this PR?

**Comment by Eternaldoom** [comment]
Because the current system is fine, and because the way you have done this would still require the names to be doubled if I'm not mistaken.

**Comment by Adaptivity** [comment]
It is not needed to double strings with my changes. All names 100% present in-game and displayed correctly. Rethink your decision if possible.

**Comment by Adaptivity** [comment]
@RadioactiveStud what do you think about it?

**Comment by sheenrox82** [comment]
Why would you add divinerpg. to entity names when Forge does it itself? With this commit you would be making it say entity.divinerpg.divinerpg.(entityname).name which is completely useless.

**Comment by sheenrox82** [comment]
How would "it prevent conflicts"? What other mod has the mod ID as "DivineRPG"?

**Comment by Adaptivity** [comment]
Ok, let's say Forge add it automatically. But why all names should be doubled? Other mods doesn't do so.

**Comment by Eternaldoom** [comment]
Because it adds them to the vanilla class to name map in order to allow spawn eggs and the /summon command. This doesn't use the prefix though.

**Pull request closed without merging**
