### PR TITLE
Add a way to disable update checker

### PR DESCRIPTION
**Pull request by xaoseric**
This should provide a way for servers to disable the updater which can cause issues for servers.

### CODE REVIEW

**Comment by xaoseric** [comment]
Fixed the if statements to make a dedicated check to see if updater is disabled or enabled

**Comment by Eternaldoom** [comment]
I'll implement this for the next update, but since it's being developed off-github I just won't merge the PR.

**Comment by kirich1368** [comment]
all exactly such an error in DivineRPG 1.4.1.3

**Comment by Eternaldoom** [comment]
Implemented in the next commit.

**Pull request closed without merging**
